server:
  port: 8080

spring:
  application:
    name: clock-in-service
  web:
    locale: en_US
  jackson:
    default-property-inclusion: non_null
    time-zone: America/New_York
  datasource:
    url: jdbc:postgresql://localhost:5432/cse310-tenants?currentSchema=tenant2&rewriteBatchedStatements=true
    username: chatting_h8k0_user
    password: 3HiVek6CuR9TKAYWPN4ZUbZ0NEESR9II
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
